wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712854527.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 50
      - 55
      3:
      - 7
      - 23
      - 60
      4: 3.10.13
      5: 0.16.6
      6: 4.36.2
      8:
      - 5
      9:
        2: lightning_fabric_logger
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
eval_interval:
  desc: null
  value: 600
save_interval:
  desc: null
  value: 1000
eval_iters:
  desc: null
  value: 100
log_interval:
  desc: null
  value: 1
devices:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.009
batch_size:
  desc: null
  value: 8.0
micro_batch_size:
  desc: null
  value: 2
gradient_accumulation_steps:
  desc: null
  value: 4.0
epoch_size:
  desc: null
  value: 1500
num_epochs:
  desc: null
  value: 1
max_iters:
  desc: null
  value: 187
weight_decay:
  desc: null
  value: 0.02
max_seq_length:
  desc: null
  value: 1024
warmup_steps:
  desc: null
  value: 187
