wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712854308.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 50
      - 55
      3:
      - 23
      4: 3.10.13
      5: 0.16.6
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
